export type ProjectSeed = {
  order: number;
  slug: string;
  title: string;
  subtitle: string;
  role: string;
  period: string;
  summary: string;
  highlights: string[];
  techStack: string[];
  githubUrl?: string;
  demoUrl?: string;
  sourceRepo?: string;
};

export type ToolCategory = { key: string; label: string };
export type ToolItem = {
  name: string;
  summary: string;
  href: string;
  category: string;
  tags: string[];
};

export const GITHUB_PROFILE_URL = "https://github.com/Wanfeng1028";

export const projectSeeds: ProjectSeed[] = [
  {
    order: 1,
    slug: "offshore-sargassum-forecast",
    title: "基于深度学习的夜间大范围海洋叶绿素浓度智能预测",
    subtitle: "LSTM + Transformer 时空预测项目",
    role: "全栈开发",
    period: "2024-03 ~ 2025-06",
    summary:
      "基于多源高分辨率遥感数据构建夜间海洋叶绿素预测系统，包含前端可视化展示、后端推理服务和模型部署。",
    highlights: [
      "建立 LSTM 与 Transformer 联合预测链路，测试集 MAE 约 0.0366，RMSE 约 0.0934",
      "前端基于 Vue3 + Mapbox GL + ECharts，实现时空可视化与动态交互",
      "后端采用 FastAPI + PostGIS + GeoJSON 管线，支持大规模空间数据处理与推理接口"
    ],
    techStack: ["Vue3", "TypeScript", "Mapbox GL", "ECharts", "FastAPI", "PostGIS", "PyTorch", "Docker"],
    githubUrl: GITHUB_PROFILE_URL
  },
  {
    order: 2,
    slug: "parrot-sound-tts",
    title: "Parrot-Sound TTS（文本转语音）AI 语音生成网站",
    subtitle: "中文 TTS 模型训练与前端站点落地",
    role: "前端开发",
    period: "2025-03 ~ 2025-09",
    summary: "围绕 TTS 模型推理链路搭建网站端到端体验，支持文本输入、语音试听、结果下载与任务状态反馈。",
    highlights: [
      "前端采用 Vue3 + TypeScript + Vite + Pinia + Element Plus，交互链路完整",
      "后端通过 FastAPI 暴露推理接口，支持异步任务队列与状态跟踪",
      "针对中文语音合成场景做参数调优，提升语音自然度与响应稳定性"
    ],
    techStack: ["Vue3", "TypeScript", "Vite", "Pinia", "Element Plus", "FastAPI", "CosyVoice"],
    githubUrl: GITHUB_PROFILE_URL
  },
  {
    order: 3,
    slug: "vessel-detection-control-platform",
    title: "海洋目标识别与雷达点云补全系统",
    subtitle: "项目负责人 / 模型训练 / 前端开发",
    role: "项目负责人 & 模型训练 & 前端开发",
    period: "2024-04 ~ 2025-08",
    summary: "面向海洋场景构建目标识别与雷达点云补全一体化平台，支持实时检测、结果追踪和可视化分析。",
    highlights: [
      "基于 YOLOv11 进行目标检测训练，核心指标 mAP 约 0.973",
      "前端使用 Vue3 + Three.js + ECharts 实现三维可视化和数据看板",
      "后端 FastAPI + OpenCV + Docker 化部署，实现稳定的实时推理链路"
    ],
    techStack: ["Vue3", "Three.js", "ECharts", "FastAPI", "OpenCV", "YOLO", "Docker"],
    githubUrl: GITHUB_PROFILE_URL
  },
  {
    order: 4,
    slug: "wanfeng-blog-web",
    title: "Wanfeng Blog Web",
    subtitle: "个人全栈博客系统",
    role: "全栈开发",
    period: "持续迭代",
    summary: "基于 Next.js App Router 的个人博客，包含内容管理、鉴权、评论、搜索、SEO 与部署链路。",
    highlights: [
      "实现前台站点 + 管理后台 + 权限控制，支持文章全流程管理",
      "集成 Prisma + PostgreSQL + Auth.js，具备完整登录安全能力",
      "支持 RSS / Sitemap / OG / 搜索能力，满足上线要求"
    ],
    techStack: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Prisma", "PostgreSQL", "Auth.js"],
    githubUrl: GITHUB_PROFILE_URL,
    demoUrl: "/"
  }
];

export const toolCategories: ToolCategory[] = [
  { key: "all", label: "全部" },
  { key: "writing", label: "AI写作工具" },
  { key: "image", label: "AI图像工具" },
  { key: "video", label: "AI视频工具" },
  { key: "productivity", label: "AI办公工具" },
  { key: "agent", label: "AI智能体" },
  { key: "chat", label: "AI聊天助手" },
  { key: "coding", label: "AI编程工具" },
  { key: "devplatform", label: "AI开发平台" },
  { key: "design", label: "AI设计工具" },
  { key: "audio", label: "AI音频工具" },
  { key: "search", label: "AI搜索引擎" },
  { key: "learning", label: "AI学习网站" },
  { key: "model", label: "AI训练模型" },
  { key: "eval", label: "AI模型评测" },
  { key: "detect", label: "AI内容检测" },
  { key: "prompt", label: "AI提示指令" },
];

export const aiTools: ToolItem[] = [
  { name: "蛙蛙写作", summary: "AI小说和内容创作工具", href: "https://wawawriter.com/app/?utm_source=aigongjuji", category: "writing", tags: ["writing"] },
  { name: "讯飞绘文", summary: "免费AI写作工具，5分钟生成一篇原创稿！", href: "https://turbodesk.xfyun.cn/?channelid=aitool1", category: "writing", tags: ["writing"] },
  { name: "笔灵AI写作", summary: "600+写作模板、AI一键生成论文/小说，论文降重降AI", href: "https://ibiling.cn/?from=ai-bot", category: "writing", tags: ["writing"] },
  { name: "新华妙笔", summary: "新华社推出的体制内办公学习平台", href: "https://miaobi.xinhuaskl.com/?channel=shuzhi", category: "writing", tags: ["writing"] },
  { name: "笔灵AI小说", summary: "AI一键写全篇+爆文拆解，搞定大纲、素材，新手写作过稿神器！", href: "https://ibiling.cn/novel-workbench/?from=aibotnovel", category: "writing", tags: ["writing"] },
  { name: "稿定AI文案", summary: "小红书、公众号、短视频AI文案生成工具", href: "https://www.gaoding.com/utms/cd3cc3a1cb0149d3bfc4a71b5e157098", category: "writing", tags: ["writing"] },
  { name: "01Agent", summary: "AI图文创作工具，支持生成、排版、编辑、发布", href: "https://ai-bot.cn/sites/69212.html", category: "writing", tags: ["writing"] },
  { name: "Paperpal", summary: "英文论文写作助手", href: "https://paperpal.cn/?utm_source=aibot&utm_medium=Banner&utm_campaign=Banner", category: "writing", tags: ["writing"] },
  { name: "笔目鱼", summary: "专业英文论文写作器", href: "https://www.bmysci.com/?channelCode=aibotad", category: "writing", tags: ["writing"] },
  { name: "稿易AI论文", summary: "AI论文写作助手，免费生成2000字大纲", href: "https://gaoyiai.com/pro", category: "writing", tags: ["writing"] },
  { name: "千笔AI论文", summary: "全网首家论文无限改稿平台", href: "https://www.qianbixiezuo.com/?pic=g5DP", category: "writing", tags: ["writing"] },
  { name: "66AI论文", summary: "高质量、低查重、低AIGC率的AI论文写作工具", href: "https://www.66paper.cn/AI_A2E1C09", category: "writing", tags: ["writing"] },
  { name: "维普科创助手", summary: "维普的一站式AI科研服务平台", href: "https://super.cqvip.com/?invite=aibot", category: "writing", tags: ["writing"] },
  { name: "沁言学术", summary: "AI科研写作平台，一站式文献管理", href: "https://www.qinyanai.com/?utm_source=ai-bot.cn", category: "writing", tags: ["writing"] },
  { name: "茅茅虫", summary: "一站式AI论文写作助手", href: "https://mymmc.cn/?fromId=954f8p78", category: "writing", tags: ["writing"] },
  { name: "GetDraft", summary: "得到推出的多AI专家协作AI写作工具", href: "https://getdraft.ai/?utm_source=ai-bot.cn", category: "writing", tags: ["writing"] },
  { name: "光速写作", summary: "AI写作、PPT生成工具，单篇最长15000字", href: "https://www.guangsuxie.com/static/college-write-web/home?from=AItools ", category: "writing", tags: ["writing"] },
  { name: "YouMind", summary: "专注提升创作效率和信息整合的AI原生工具", href: "https://youmind.com/invite/84LX6W", category: "writing", tags: ["writing"] },
  { name: "万能小in", summary: "3分钟4万字150+应用，只需标题，快速生成毕业论文", href: "https://xiaoin.com.cn/home/index?sharerUserId=1815301629231030274", category: "writing", tags: ["writing"] },
  { name: "墨问", summary: "专为创作者设计的AI笔记工具", href: "https://mowen.cn/?utm_source=ai-bot.cn", category: "writing", tags: ["writing"] },
  { name: "材料星AI", summary: "专为秘书工作设计的AI写作工具", href: "https://cailiaoxing.com/?utm_source=ai-bot.cn", category: "writing", tags: ["writing"] },
  { name: "FeelFish", summary: "专为小说创作者打造的 AI 写作 PC 客户端软件", href: "https://www.feelfish.com/?fr=aibot", category: "writing", tags: ["writing"] },
  { name: "Loomi", summary: "创作版Claude Code，AI原生写作工具", href: "https://loomi.live/?utm_source=ai-bot.cn", category: "writing", tags: ["writing"] },
  { name: "落笔AI写作", summary: "专注于小说网文创作的AI写作工具", href: "https://luobi.net/?utm_source=ai-bot.cn", category: "writing", tags: ["writing"] },
  { name: "ReadPo", summary: "AI读写助手，支持内容聚合快速阅读并总结", href: "https://ai-bot.cn/readpo", category: "writing", tags: ["writing"] },
  { name: "小鱼AI写作", summary: "一站式AI写作平台，一键生成高质量原创内容", href: "https://www.xiaoyuxiezuo.com/AI_A2E1C09", category: "writing", tags: ["writing"] },
  { name: "量子探险", summary: "AI小说写作工具，长文本一键生成", href: "https://www.yfbudong.com/?utm_source=ai-bot.cn", category: "writing", tags: ["writing"] },
  { name: "社研通", summary: "专注于服务文科研究生的多模态AI学术写作工具", href: "https://www.sheyantong.cn/?utm_source=ai-bot.cn", category: "writing", tags: ["writing"] },
  { name: "Rubriq", summary: "免费试用，AI学术论文润色与翻译工具", href: "https://rubriq.cn/?utm_source=ai&utm_medium=ai-bot&utm_campaign=2025rubriq_cn", category: "writing", tags: ["writing"] },
  { name: "QuillBot", summary: "AI英/德语写作润色和改进工具", href: "https://try.quillbot.com/6eqrqpoysmlh", category: "writing", tags: ["writing"] },
  { name: "LiblibAI", summary: "一站式 AI 内容创作生成平台", href: "https://www.liblib.art/video-effect?sourceid=004810", category: "video", tags: ["video"] },
  { name: "绘蛙AI视频", summary: "绘蛙推出的AI图生视频工具", href: "https://www.ihuiwa.com/workspace/ai-video/custom-action?huiwaInviteCode=EMRCAL", category: "video", tags: ["video"] },
  { name: "SoundView", summary: "Sora视频去水印，AI视频本地化工具", href: "https://soundviewai.com/invitation?inviteCode=H6tVloZUV&from=aibot", category: "video", tags: ["video"] },
  { name: "Vidu", summary: "生数科技推出的AI视频生成大模型", href: "https://www.vidu.cn/?utm_source=ai-bot.cn", category: "video", tags: ["video"] },
  { name: "有言", summary: "一站式AI视频创作和3D数字人生成平台", href: "https://www.youyan3d.com/login/?utm_source=zhanwaidaoliu&utm_campaign=zwj&utm_content=aigongjuji&from=aigongjuji", category: "video", tags: ["video"] },
  { name: "HeyGen", summary: "专业的AI数字人视频创作平台", href: "https://heygen.com/?sid=rewardful&via=ai-bot", category: "video", tags: ["video"] },
  { name: "堆友AI视频", summary: "堆友AI推出的免费AI视频生成工具", href: "https://d.design/ai/video?from=ab13", category: "video", tags: ["video"] },
  { name: "白日梦", summary: "领先AI创作平台，可生成最长50分钟的视频", href: "https://aibrm.paluai.com/bairimeng", category: "video", tags: ["video"] },
  { name: "即梦AI", summary: "一站式AI视频、图片、数字人创作工具", href: "https://jimeng.jianying.com/?utm_source=ai-bot.cn", category: "video", tags: ["video"] },
  { name: "Pollo AI", summary: "一站式AI图像和视频创作平台", href: "https://fas.st/t/nFLHVC4T", category: "video", tags: ["video"] },
  { name: "Keevx", summary: "开箱即用的AI数字人视频创作工具", href: "https://keevx.baidu.com/zh?utm_source=aibot&utm_medium=affiliate&utm_campaign=whkj", category: "video", tags: ["video"] },
  { name: "Sora", summary: "OpenAI推出的AI视频生成模型", href: "https://sora.chatgpt.com", category: "video", tags: ["video"] },
  { name: "蝉镜", summary: "AI数字人视频生成平台", href: "https://www.chanjing.cc/refc/?type=hzBuy&id=BEB41KJUj-n9rTc5kxR5WGKv6bdmvm_rv5Qpxs0XNFc", category: "video", tags: ["video"] },
  { name: "JoyPix", summary: "AI数字人创作工具，支持声音克隆", href: "https://www.joypix.ai/app/login/?utm=cg&cgv=aibotcn", category: "video", tags: ["video"] },
  { name: "可灵AI", summary: "快手推出的AI视频生成工具", href: "https://kling.kuaishou.com/?utm_source=ai-bot.cn", category: "video", tags: ["video"] },
  { name: "海螺视频", summary: "MiniMax公司推出的AI视频生成工具", href: "https://ai-bot.cn/hailuoai-video", category: "video", tags: ["video"] },
  { name: "腾讯混元AI视频", summary: "腾讯推出的AI视频生成工具", href: "https://video.hunyuan.tencent.com/?utm_source=ai-bot.cn", category: "video", tags: ["video"] },
  { name: "通义万相AI视频", summary: "通义万相AI视频是阿里推出的...", href: "https://ai-bot.cn/tongyi-wanxvideo", category: "video", tags: ["video"] },
  { name: "魔珐星云", summary: "具身智能3D数字人开放平台", href: "https://www.xingyun3d.com/?utm_source=zhanwaidaoliu&utm_campaign=zwj&utm_content=aibot", category: "video", tags: ["video"] },
  { name: "AdsTurbo AI", summary: "AI视频广告生成平台，自动生成可直接投放的视频", href: "https://adsturbo.ai/?utm_source=ai-bot.cn", category: "video", tags: ["video"] },
  { name: "献丑AI", summary: "首个 AI 视频开源社区，支持一键Fork与共创", href: "https://xianchou.com/?utm_source=ai-bot.cn", category: "video", tags: ["video"] },
  { name: "MochiAni", summary: "AI动画视频创作工具", href: "https://www.mochiani.com/?utm_source=ai-bot.cn", category: "video", tags: ["video"] },
  { name: "TapNow", summary: "AI视觉内容创作平台，提供多种预设工作流", href: "https://www.tapnow.ai/?utm_source=ai-bot.cn", category: "video", tags: ["video"] },
  { name: "Higgsfield", summary: "AI视频生成工具，支持专业运镜效果", href: "https://higgsfield.ai/?utm_source=ai-bot.cn", category: "video", tags: ["video"] },
  { name: "雾象", summary: "免费开源的AI动画生成工具", href: "https://fogsight.ai/?utm_source=ai-bot.cn", category: "video", tags: ["video"] },
  { name: "造次", summary: "AI原创IP视频社区", href: "https://www.zaoci.tv/?utm_source=ai-bot.cn", category: "video", tags: ["video"] },
  { name: "造点AI", summary: "夸克团队推出的AI图像与视频创作平台", href: "https://www.zaodian.com/?utm_source=ai-bot.cn", category: "video", tags: ["video"] },
  { name: "花生AI", summary: "B站推出的AI视频创作工具", href: "https://www.huasheng.cn/?utm_source=ai-bot.cn", category: "video", tags: ["video"] },
  { name: "NextCut AI", summary: "AI视频创作工具，集成无限画布 + workflow + 剪辑轨道 + 多Agent团队", href: "https://nextcut-ai.com/?utm_source=ai-bot.cn", category: "video", tags: ["video"] },
  { name: "云幕同声", summary: "专业AI视频翻译，短剧出海、跨境电商，效果超棒！", href: "https://www.yunmuts.com/?from=ai-bot", category: "video", tags: ["video"] },
  { name: "Atoms", summary: "第一支自动构建真实业务的 AI 团队", href: "https://mgx.dev/?utm_source=aidirectory&utm_medium=aibot&utm_campaign=pay_per_action", category: "agent", tags: ["agent"] },
  { name: "爱派AiPy", summary: "本地Manus、国内能用、内网能用，开源免费", href: "https://www.aipyaipy.com/?referral=C21SJ", category: "agent", tags: ["agent"] },
  { name: "扣子", summary: "免费全能的AI办公智能体", href: "https://dis.csqixiang.cn/unpo/cozeaibot.html", category: "agent", tags: ["agent"] },
  { name: "讯飞星辰Agent", summary: "科大讯飞推出的AI智能体开发平台", href: "https://agent.xfyun.cn/home?ch=xcagent-aitool1", category: "agent", tags: ["agent"] },
  { name: "Manus", summary: "蝴蝶效应公司推出的首款自主通用AI Agent", href: "https://manus.im/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "Flowith", summary: "免费用Gemini 3、GPT-5", href: "https://flowith.paluai.com/aibot", category: "agent", tags: ["agent"] },
  { name: "码上飞", summary: "一句话生成微信小程序、APP、H5网页", href: "https://ai-bot.cn/sites/60995.html", category: "agent", tags: ["agent"] },
  { name: "金灵AI", summary: "专业的金融深度投研AI Agent", href: "https://www.gilin.com.cn/?channel=c02", category: "agent", tags: ["agent"] },
  { name: "OiiOii", summary: "全球首个专业动画创作Agent", href: "https://www.oiioii.ai/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "AnyGen", summary: "字节跳动推出的AI办公智能体", href: "https://www.anygen.io/home?invitation_code=HQUCT0VDOZLXK17", category: "agent", tags: ["agent"] },
  { name: "Tbox", summary: "蚂蚁集团旗下多智能体协同的通用 AI Agent", href: "https://www.tbox.cn/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "EvoMap", summary: "全球首个面向 AI 智能体的进化协作平台", href: "https://evomap.ai/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "happycapy", summary: "Trickle 团队推出的云端AI Agent原生计算机", href: "https://happycapy.ai/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "Genspark", summary: "通用AI智能体，您的一站式AI工作空间", href: "https://www.genspark.ai/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "小云雀", summary: "字节跳动旗下剪映推出的AI内容创作Agent", href: "https://xyq.jianying.com/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "Operator", summary: "OpenAI推出的AI智能体，能推理、联网自主执行任务", href: "https://ai-bot.cn/operator", category: "agent", tags: ["agent"] },
  { name: "GenFlow", summary: "全球首个全模态、全端通用AI智能体", href: "https://wenku.baidu.com/ndcore/browse/aiunion?tabType=genflow?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "OpenClaw", summary: "开源免费的个人 AI 助手", href: "https://clawd.bot/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "Lovart", summary: "LiblibAI推出的全球首个设计智能体", href: "https://www.lovart.ai/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "Skywork", summary: "昆仑万维面向全球推出的天工超级智能体", href: "https://ai-bot.cn/skywork", category: "agent", tags: ["agent"] },
  { name: "切问学术", summary: "FudanNLP团队推出的AI学术智能体", href: "https://qiewenpaper.com/zh?utm_source=aibot", category: "agent", tags: ["agent"] },
  { name: "Leewow", summary: "首个造物 AI Agent，图片或文本生成实物商品", href: "https://www.leewow.com/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "Mixboard", summary: "Google Labs 推出的 AI 无限画布工具", href: "https://mixboard.google.com/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "memU Bot", summary: "7*24小时全天候运行的AI个人助手", href: "https://memu.bot/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "元气AI Bot", summary: "猎豹推出的电脑全能AI伙伴，国产OpenClaw", href: "https://yuanqiai.net/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "WorkAny", summary: "本地运行的开源AI桌面智能体", href: "https://workany.ai/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "Agnes AI", summary: "专为办公场景设计的团队协作型AI Agent", href: "https://agnes-ai.com/?utm_source=ai-bot.cn", category: "agent", tags: ["agent"] },
  { name: "Seele AI", summary: "全球首个端到端AI 3D游戏生成工具", href: "https://seelesai.go.link/kw8uW", category: "agent", tags: ["agent"] },
  { name: "稿定AI社区", summary: "稿定推出的设计Agent和AI创意社区", href: "https://www.gaoding.art/utms/64e4e1421ad845ca94125ffb1c90ccdd", category: "agent", tags: ["agent"] },
  { name: "豆包", summary: "智能对话助手，办公创作全能！", href: "https://www.doubao.com/?channel=aibot&source=hw_db_aibot&type=daoh&theme=ai", category: "chat", tags: ["chat"] },
  { name: "讯飞星火", summary: "AI智能助手，免费PPT生成、深度研究", href: "https://ai-bot.cn/xinghuo-xfyun", category: "chat", tags: ["chat"] },
  { name: "腾讯元宝", summary: "腾讯推出的免费AI智能助手", href: "https://yuanbao.paluai.com/aibot", category: "chat", tags: ["chat"] },
  { name: "ChatGPT", summary: "OpenAI 推出的AI聊天机器人", href: "https://chatgpt.com", category: "chat", tags: ["chat"] },
  { name: "Claude", summary: "Anthropic公司推出的对话式AI智能助手", href: "https://ai-bot.cn/sites/460.html", category: "chat", tags: ["chat"] },
  { name: "Gemini", summary: "Google推出的AI聊天对话机器人Gemini", href: "https://deepmind.google/technologies/gemini", category: "chat", tags: ["chat"] },
  { name: "逗逗AI", summary: "AI游戏陪玩，支持原神、黑神话、LOL！", href: "https://doudou.paluai.com/web_aitool", category: "chat", tags: ["chat"] },
  { name: "DeepSeek", summary: "幻方量化推出的AI智能助手和开源大模型", href: "https://deepseek.com/?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "Kimi智能助手", summary: "月之暗面推出的AI智能助手", href: "https://www.kimi.com/?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "千问", summary: "全能AI助手，基于Qwen模型", href: "https://dis.chatdesks.cn/chatdesk/tyaibot.html", category: "chat", tags: ["chat"] },
  { name: "Grok", summary: "马斯克旗下xAI推出的人工智能助手", href: "https://grok.com", category: "chat", tags: ["chat"] },
  { name: "Z.ai", summary: "智谱面向全球推出的AI模型体验平台", href: "https://z.ai/?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "Qwen Chat", summary: "阿里通义推出的 Qwen 最新模型体验平台", href: "https://ai-bot.cn/qwen-chat", category: "chat", tags: ["chat"] },
  { name: "MiniMax", summary: "MiniMax推出的AI智能问答助手", href: "https://chat.minimaxi.com/?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "LongCat", summary: "美团推出的自研大模型AI对话平台", href: "https://longcat.chat/?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "文心一言", summary: "百度推出的基于文心大模型的AI智能助手", href: "https://yiyan.baidu.com/?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "智谱清言", summary: "智谱推出的全能AI助手", href: "https://chatglm.cn/?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "华为小艺", summary: "华为旗下小艺AI助手网页端，已接入DeepSeek-R1", href: "https://ai-bot.cn/huawei-xiaoyi", category: "chat", tags: ["chat"] },
  { name: "问小白", summary: "AI智能助手，支持DeepSeek满血版", href: "https://www.wenxiaobai.com/?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "百灵大模型", summary: "蚂蚁集团推出的 Ling-1T 大模型对话体验平台", href: "https://ling.tbox.cn/chat?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "书生大模型", summary: "上海人工智能实验室推出的系列AI模型", href: "https://ai-bot.cn/sites/53308.html", category: "chat", tags: ["chat"] },
  { name: "阶跃AI", summary: "阶跃星辰推出的支持多模态的AI聊天机器人", href: "https://www.stepfun.com/chats/new?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "百小应", summary: "百川智能推出的免费AI助手", href: "https://ying.baichuan-ai.com/chat?from=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "天工AI", summary: "昆仑万维推出的AI智能助手", href: "https://www.tiangong.cn/?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "商量SenseChat", summary: "商汤科技推出的免费AI聊天助手", href: "https://chat.sensetime.com/wb/home?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "Me.bot", summary: "心识宇宙推出的个性化AI伴侣产品", href: "https://www.me.bot/?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "Saylo", summary: "AI驱动的故事角色扮演游戏应用，沉浸式的剧本互动体验", href: "https://www.sayloai.com/?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "Poe", summary: "问答社区Quora推出的问答机器人工具", href: "https://poe.com/?utm_source=ai-bot.cn", category: "chat", tags: ["chat"] },
  { name: "Copilot", summary: "微软推出的网页版Copilot助手", href: "https://copilot.microsoft.com", category: "chat", tags: ["chat"] },
  { name: "TRAE", summary: "字节跳动推出的 AI IDE 编程工具", href: "https://www.trae.cn/?utm_source=advertising&utm_medium=aibot_ug_cpa&utm_term=hw_trae_aibot", category: "coding", tags: ["coding"] },
  { name: "秒哒", summary: "无代码AI应用开发平台，一句话做应用", href: "https://ai-bot.cn/sites/65909.html", category: "coding", tags: ["coding"] },
  { name: "代码小浣熊", summary: "商汤科技推出的免费AI编程助手", href: "https://www.xiaohuanxiong.com/login?utm_source=blmay1", category: "coding", tags: ["coding"] },
  { name: "文心快码", summary: "百度推出的AI编程助手，基于文心大模型", href: "https://comate.baidu.com/?inviteCode=8f8or9cz", category: "coding", tags: ["coding"] },
  { name: "Qoder", summary: "阿里巴巴推出的 AI Agentic 编程工具", href: "https://qoder.com/?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "Cursor", summary: "AI代码编辑器，快速进行编程和软件开发", href: "https://www.cursor.com/?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "豆包AI编程", summary: "豆包推出的AI编程新功能", href: "https://ai-bot.cn/doubao-aicoding", category: "coding", tags: ["coding"] },
  { name: "OpenCode", summary: "开源 AI 编程工具 ， Claude Code 最佳平替", href: "https://opencode.ai/?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "Kilo Code", summary: "开源的 AI 编程扩展插件", href: "https://kilo.ai/?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "Google Antigravity", summary: "谷歌推出的 AI IDE 编程智能体", href: "https://antigravity.google/?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "Claude Code", summary: "Anthropic 推出的AI编程工具", href: "https://www.anthropic.com/claude-code?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "Kiro", summary: "亚马逊公司推出的 AI IDE", href: "https://kiro.dev/?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "Codex", summary: "OpenAI推出的AI编程模型和工具", href: "https://openai.com/index/codex-now-generally-available", category: "coding", tags: ["coding"] },
  { name: "YouWare", summary: "一站式 AI 编程社区与开发平台", href: "https://www.youware.com/?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "Zcode", summary: "智谱推出的轻量级AI IDE编程工具", href: "https://zcode-ai.com/?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "CodeBuddy IDE", summary: "腾讯推出的全栈开发AI IDE", href: "https://www.codebuddy.ai/?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "Lovable", summary: "全栈AI编程工具，一句话构建网站应用", href: "https://lovable.dev/?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "CatPaw", summary: "美团推出的 AI IDE 编程工具", href: "https://catpaw.meituan.com/?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "Augment Code", summary: "AI编程辅助工具，专为大型代码库设计", href: "https://www.augmentcode.com/?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "MonkeyCode", summary: "长亭科技开源的 AI 编程助手与企业级开发平台", href: "https://monkeycode-ai.com/?ic=019aa59c-eb57-7c35-b163-8f73ced7e522", category: "coding", tags: ["coding"] },
  { name: "iFlow CLI", summary: "心流AI推出的免费终端 AI 智能体", href: "https://cli.iflow.cn/?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "通义灵码", summary: "阿里推出的免费AI编程工具，基于通义大模型", href: "https://lingma.aliyun.com/lingma", category: "coding", tags: ["coding"] },
  { name: "GitHub Copilot", summary: "GitHub推出的AI编程工具", href: "https://github.com/features/copilot", category: "coding", tags: ["coding"] },
  { name: "Firebase Studio", summary: "谷歌推出的AI编程工具，一站式开发全栈应用", href: "https://ai-bot.cn/firebase-studio", category: "coding", tags: ["coding"] },
  { name: "Windsurf", summary: "Codeium公司推出的AI编程工具", href: "https://ai-bot.cn/windsurf", category: "coding", tags: ["coding"] },
  { name: "Bolt.new", summary: "StackBlitz 推出的全栈AI代码工具，可以看作 Artfacts、V0 和 Replit 的结合体", href: "https://ai-bot.cn/bolt%E2%80%A4new", category: "coding", tags: ["coding"] },
  { name: "InfCode", summary: "词元无限推出的企业级AI编程工具", href: "https://www.tokfinity.com/infcode?utm_source=ai-bot.cn", category: "coding", tags: ["coding"] },
  { name: "CodeFlicker", summary: "快手推出的AI原生IDE编程工具", href: "https://www.codeflicker.ai", category: "coding", tags: ["coding"] },
  { name: "Clacky AI", summary: "AI编程工具，打造L3级的Coding Studio", href: "https://ai-bot.cn/clacky-ai", category: "coding", tags: ["coding"] },
  { name: "Replit Agent", summary: "AI初创公司Replit推出的AI编程工具", href: "https://ai-bot.cn/replit-agent", category: "coding", tags: ["coding"] },
  { name: "Coze", summary: "海量AI智能体免费用，一键复制同款", href: "https://www.coze.cn/?utm_medium=daohang&utm_source=aibot&utm_content=&utm_id=&utm_campaign=&utm_term=49156769m&utm_source_platform=", category: "devplatform", tags: ["devplatform"] },
  { name: "响指HaiSnap", summary: "AI零代码应用开发平台，可视化编辑迭代", href: "https://www.haisnap.com/?channel=ai_bot", category: "devplatform", tags: ["devplatform"] },
  { name: "BigModel", summary: "GLM-5编程能力媲美Claude Sonnet 4.5，首购5折！", href: "https://www.bigmodel.cn/glm-coding?ic=LAKDCB3VMB", category: "devplatform", tags: ["devplatform"] },
  { name: "ZenMux", summary: "全球首个带保险赔付机制的企业级大模型聚合平台", href: "https://zenmux.ai/invite/5MQIGW", category: "devplatform", tags: ["devplatform"] },
  { name: "英博云AI算力", summary: "英博数科推出的GPU智算服务云平台", href: "https://www.ebcloud.com/chn_zu3hgw9a", category: "devplatform", tags: ["devplatform"] },
  { name: "Google AI Studio", summary: "免费体验和测试 Google 最新的 AI 模型", href: "https://aistudio.google.com/?utm_source=ai-bot.cn", category: "devplatform", tags: ["devplatform"] },
  { name: "阿里云百炼", summary: "一站式大模型开发与应用构建平台（免费领5.5折优惠券）", href: "https://www.aliyun.com/minisite/goods?userCode=ex9ez2fz", category: "devplatform", tags: ["devplatform"] },
  { name: "Zion", summary: "全栈开发AI Agent应用的无代码开发平台", href: "https://ai-bot.cn/zion", category: "devplatform", tags: ["devplatform"] },
  { name: "n8n", summary: "开源的低代码AI工作流自动化工具", href: "https://n8n.io/?utm_source=ai-bot.cn", category: "devplatform", tags: ["devplatform"] },
  { name: "Dify", summary: "开源的生成式AI应用开发平台", href: "https://ai-bot.cn/dify", category: "devplatform", tags: ["devplatform"] },
  { name: "FastGPT", summary: "免费AI工作流搭建工具 自动化提高效率", href: "https://cloud.fastgpt.cn/dashboard/templateMarket?utm_source=ad&utm_medium=aibot&utm_content=aibot", category: "devplatform", tags: ["devplatform"] },
  { name: "灵光", summary: "蚂蚁推出的AI对话与应用生成平台", href: "https://www.lingguang.com/chat?utm_source=ai-bot.cn", category: "devplatform", tags: ["devplatform"] },
  { name: "快马InsCode", summary: "通过对话、设计图或文章链接生成工程项目代码", href: "https://www.inscode.net/?utm_source=aibot", category: "devplatform", tags: ["devplatform"] },
  { name: "BASE44", summary: "零代码AI应用开发平台", href: "https://ai-bot.cn/base44", category: "devplatform", tags: ["devplatform"] },
  { name: "Trickle AI", summary: "一站式无代码 AI 开发平台", href: "https://trickle.so/?utm_source=ai-bot.cn", category: "devplatform", tags: ["devplatform"] },
  { name: "Refly", summary: "全球首个开源 Vibe Workflow 平台", href: "https://refly.ai/?utm_source=ai-bot.cn", category: "devplatform", tags: ["devplatform"] },
  { name: "NoCode", summary: "美团推出的零代码AI应用开发平台", href: "https://ai-bot.cn/nocode", category: "devplatform", tags: ["devplatform"] },
  { name: "OpenRouter", summary: "AI 模型 API 聚合平台，一个接口调用400多个模型", href: "https://openrouter.ai/?utm_source=ai-bot.cn", category: "devplatform", tags: ["devplatform"] },
  { name: "SiliconFlow", summary: "生成式AI计算基础设施平台", href: "https://cloud.siliconflow.cn/i/SjhsJgfH", category: "devplatform", tags: ["devplatform"] },
  { name: "数眼智能AI", summary: "企业级AI数据与模型服务平台", href: "https://shuyanai.com/?utm_source=ai-bot.cn", category: "devplatform", tags: ["devplatform"] },
  { name: "SophNet", summary: "DeepSeek API 推理速度最快的平台，没有之一", href: "https://www.sophnet.com/#?code=OMQFR0", category: "devplatform", tags: ["devplatform"] },
  { name: "晨涧云", summary: "AI算力平台，GPU算力租赁、开箱即用", href: "https://www.mornai.cn/?utm_source=ai-bot.cn", category: "devplatform", tags: ["devplatform"] },
  { name: "LLaMA-Factory Online", summary: "在线AI大模型微调平台，零代码、可视化操作", href: "https://www.llamafactory.online/register?utm_source=aigjj", category: "devplatform", tags: ["devplatform"] },
  { name: "大模型实验室", summary: "在线大模型训练微调及AI科研学习平台", href: "https://www.lab4ai.cn/register?utm_source=ai_bot", category: "devplatform", tags: ["devplatform"] },
  { name: "APIMart", summary: "一站式 AI API 平台，多主流模型统一访问", href: "https://apimart.ai/?utm_source=ai-bot.cn", category: "devplatform", tags: ["devplatform"] },
  { name: "DMXAPI", summary: "一个Key用全球大模型", href: "https://dmxapi.cn/?utm_source=ai-bot.cn", category: "devplatform", tags: ["devplatform"] },
  { name: "小马算力", summary: "AI模型API聚合平台，自由调用不同模型", href: "https://www.tokenpony.cn/5EN1y", category: "devplatform", tags: ["devplatform"] },
  { name: "堆友AI", summary: "专为设计师打造的AI设计服务平台", href: "https://d.design/?from=ab13", category: "design", tags: ["design"] },
  { name: "星流AI", summary: "LiblibAI推出的一站式 AI 设计与创作工具", href: "https://www.xingliu.art/?sourceid=005348", category: "design", tags: ["design"] },
  { name: "绘蛙", summary: "AI电商设计工具", href: "https://ai-bot.cn/sites/9195.html", category: "design", tags: ["design"] },
  { name: "稿定AI", summary: "一站式AI创作和设计平台", href: "https://www.gaoding.com/utms/1591aff1eb344c64a364a5e6dd7fcbdd", category: "design", tags: ["design"] },
  { name: "墨刀AI", summary: "AI秒生原型稿", href: "https://modao.cc/feature/ai?utm_channel=wl&utm_source=referrals&utm_keyword=aibot", category: "design", tags: ["design"] },
  { name: "Figma AI", summary: "Figma推出的原生AI设计工具", href: "https://www.figma.com/ai/?utm_source=ai-bot.cn", category: "design", tags: ["design"] },
  { name: "美图设计室", summary: "AI图像创作和设计平台", href: "https://www.designkit.cn/?channel=10026", category: "design", tags: ["design"] },
  { name: "135 AI排版", summary: "公众号AI图文排版和智能文案生成工具", href: "https://www.135editor.com/ai_editor/?track_id=34&hmmd=ai-bot.cn", category: "design", tags: ["design"] },
  { name: "Holopix AI", summary: "专为游戏、动漫、插画设计打造的AI设计平台", href: "https://holopix.cn/?inviteCode=741737", category: "design", tags: ["design"] },
  { name: "Pixso AI", summary: "Pixso推出的AI设计工具", href: "https://ai.pixso.cn/?utm_source=referrals&utm_content=aibot&_channel_track_key=oAa3vUM4", category: "design", tags: ["design"] },
  { name: "Recraft AI", summary: "免费无限AI画板，生成高质量矢量艺术画、图标、3D图片和插画", href: "https://www.recraft.ai/?ref=ai-bot.cn", category: "design", tags: ["design"] },
  { name: "创客贴AI", summary: "AI辅助的智能在线设计工具", href: "https://aiart.chuangkit.com/matrix?utm_source=aibotQD", category: "design", tags: ["design"] },
  { name: "Onlook", summary: "开源AI视觉编辑工具，设计修改自动同步代码", href: "https://ai-bot.cn/onlook", category: "design", tags: ["design"] },
  { name: "GemDesign", summary: "AI原生高保真原型设计工具", href: "https://design.gemcoder.com/?ci=bot", category: "design", tags: ["design"] },
  { name: "Pic Copilot", summary: "阿里国际推出的AI电商设计工具", href: "https://www.piccopilot.com/create/?utm_source=aff&utm_medium=aibot1", category: "design", tags: ["design"] },
  { name: "魔力工作室", summary: "Canva可画推出的一站式AI创作套件", href: "https://www.canva.cn/magic/?utm_source=ai-bot.cn", category: "design", tags: ["design"] },
  { name: "蚂上有创意", summary: "支付宝推出的AI设计工具，面向商家提供电商设计服务", href: "https://idesign.alipay.com/?utm_source=ai-bot.cn", category: "design", tags: ["design"] },
  { name: "爱设计", summary: "AI在线设计平台，提供多端在线拖拽设计工具", href: "https://www.isheji.com/?utm_source=ai-bot.cn", category: "design", tags: ["design"] },
  { name: "小墨鹰编辑器", summary: "行业首创的AI公众号排版工具，30s搞定推文排版！", href: "https://www.xmyeditor.com/?utm_source=ai-bot.cn", category: "design", tags: ["design"] },
  { name: "美间AI", summary: "新一代AI画布式创意设计平台", href: "https://www.meijian.com/ai?utm_source=ai-bot.cn", category: "design", tags: ["design"] },
  { name: "Calicat", summary: "ProcessOn团队推出的一站式产设研协作平台", href: "https://www.calicat.cn/?utm_source=ai-bot.cn", category: "design", tags: ["design"] },
  { name: "Microsoft Designer", summary: "微软推出的在线设计海报和宣传图工具", href: "https://designer.microsoft.com", category: "design", tags: ["design"] },
  { name: "UXbot", summary: "AI产品设计工具，一键生成UI与交互式原型", href: "https://www.uxbot.cn/?utm_source=ai-bot.cn", category: "design", tags: ["design"] },
  { name: "燕雀光年", summary: "AI LOGO设计工具", href: "https://www.yanqueai.com", category: "design", tags: ["design"] },
  { name: "标小智LOGO生成器", summary: "AI Logo设计平台，一键生成企业Logo", href: "https://www.logosc.cn/?utm_source=ai-bot.cn", category: "design", tags: ["design"] },
  { name: "Looka", summary: "AI在线设计和生成logo", href: "https://looka.com", category: "design", tags: ["design"] },
  { name: "智绘设计", summary: "腾讯推出的智能设计平台，让内容更精彩", href: "https://taishan.qq.com/brand/?ref=ai-bot.cn", category: "design", tags: ["design"] },
  { name: "MasterGo AI", summary: "国产产品设计工具MasterGo推出的智能UI设计助手", href: "https://mastergo.com/ai?utm_source=ai-bot.cn", category: "design", tags: ["design"] },
  { name: "居然设计家", summary: "居然之家联合阿里推出的AI家装设计平台", href: "https://ai-bot.cn/design-shejijia", category: "design", tags: ["design"] },
  { name: "FigJam AI", summary: "Figma推出的AI白板协作设计工具", href: "https://www.figma.com/figjam/ai", category: "design", tags: ["design"] },
  { name: "魔音工坊", summary: "AI配音工具，轻松配出媲美真人的声音", href: "https://www.moyin.com/?channelCode=AIGJJ01_20240905", category: "audio", tags: ["audio"] },
  { name: "讯飞智作", summary: "科大讯飞推出的AI转语音和配音工具", href: "https://peiyin.xunfei.cn/?ftype=14", category: "audio", tags: ["audio"] },
  { name: "Suno", summary: "高质量的AI音乐创作平台", href: "https://www.suno.ai/?ref=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "讯飞译制", summary: "科大讯飞推出的AI音视频本地化平台", href: "https://yizhi.iflyrec.com/?regFrom=XFTJ929&id=XFTJ929", category: "audio", tags: ["audio"] },
  { name: "海绵音乐", summary: "字节跳动推出的免费AI音乐创作和发现平台", href: "https://www.haimian.com/?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "Keevx声音克隆", summary: "Keevx推出的AI声音克隆工具", href: "https://keevx.baidu.com/zh/feature/avatarVoice?utm_source=aibot&utm_medium=affiliate&utm_campaign=whkj", category: "audio", tags: ["audio"] },
  { name: "ElevenLabs", summary: "AI文本转语音，支持包含中文在内的29种语言", href: "https://try.elevenlabs.io/mqbahm8egbk8", category: "audio", tags: ["audio"] },
  { name: "琅琅配音", summary: "智能文本转语音工具", href: "https://lang123.top/?rmd=64546", category: "audio", tags: ["audio"] },
  { name: "千音漫语", summary: "AI声音创作助手，支持声音克隆", href: "https://ai-bot.cn/qianyin", category: "audio", tags: ["audio"] },
  { name: "Noiz AI", summary: "AI配音工具，支持文本转语音和声音克隆", href: "https://ai-bot.cn/noiz-ai", category: "audio", tags: ["audio"] },
  { name: "MiniMax Audio", summary: "MiniMax推出的AI语音合成工具，支持声音克隆", href: "https://ai-bot.cn/minimax-audio", category: "audio", tags: ["audio"] },
  { name: "Tunee", summary: "首个对话式音乐创作AI智能体", href: "https://www.tunee.ai/?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "讯飞听见", summary: "科大讯飞推出的在线AI语音转文字工具", href: "https://www.iflyrec.com/zhuanwenzi.html?from=ai-bot_zwz", category: "audio", tags: ["audio"] },
  { name: "NotebookLM", summary: "谷歌推出的AI笔记应用，5分钟生成一段对话播客", href: "https://notebooklm.google/?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "Vemus未音", summary: "腾讯音乐旗下首款一站式AI音乐创作工具", href: "https://y.qq.com/vemus/index.html?adtag=aibot_ai_musictool_homepage", category: "audio", tags: ["audio"] },
  { name: "Nafy AI", summary: "在线 AI 音乐生成器，支持扩展、替换、翻唱", href: "https://nafy.ai/?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "TurboScribe", summary: "专业 AI 音视频转文字工具", href: "https://turboscribe.ai/?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "多维视界", summary: "一站式AI音视频智能分析平台", href: "https://dwsj.cn/?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "天谱乐", summary: "唱鸭团队推出的首个多模态音乐生成大模型", href: "https://ai-bot.cn/tianpuyue", category: "audio", tags: ["audio"] },
  { name: "音疯", summary: "昆仑万维推出的AI音乐创作平台，一键生成原创歌曲", href: "https://www.yinfeng.cn/home?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "Mureka", summary: "昆仑万维推出的 AI 音乐商用创作平台", href: "https://ai-bot.cn/mureka", category: "audio", tags: ["audio"] },
  { name: "音潮", summary: "全栈自研的AI音乐创作平台", href: "https://www.yinchaoyongxian.com/?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "音剪", summary: "喜马拉雅推出的一站式AI音频创作平台", href: "https://audioeditor.ximalaya.com/?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "音秘", summary: "百度推出的AI播客创作工具", href: "https://audiomyst.baidu.com/?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "MemoAI", summary: "免费的AI语音转文字工具", href: "https://memo.ac/?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "Reecho睿声", summary: "超拟真的中英文AI语音克隆/生成平台", href: "https://www.reecho.ai/?ref=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "Udio", summary: "免费的AI音乐创作工具，每月可生成1200首歌曲", href: "https://www.udio.com/?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "网易天音", summary: "网易推出的一站式AI音乐创作工具", href: "https://tianyin.163.com/?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "Lyrics Into Song AI", summary: "在线AI音乐创作工具，输入歌词创建个性化歌曲", href: "https://lyricsintosong.ai/zh?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "Stable Audio", summary: "Stability AI最新推出的音乐生成工具", href: "https://www.stableaudio.com/?utm_source=ai-bot.cn", category: "audio", tags: ["audio"] },
  { name: "夸克AI", summary: "集AI搜索、网盘、文档、创作等功能于一体的应用", href: "https://b.quark.cn/apps/qkhomepage_twofoufeb/routes/model?entry=other_baoyingpckk_cpa9&ch=other_baoyingpckk_cpa9&image=search&dp=", category: "search", tags: ["search"] },
  { name: "秘塔AI搜索", summary: "最好用的AI搜索工具，没有广告，直达结果", href: "https://metaso.cn/?s=aibot1&referrer_s=aibot1", category: "search", tags: ["search"] },
  { name: "Perplexity", summary: "AI搜索引擎与深度研究工具", href: "https://www.perplexity.ai/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "玻尔", summary: "新一代科研知识库与AI学术搜索平台", href: "https://www.bohrium.com/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "SearchGPT", summary: "OpenAI最新推出的AI搜索引擎", href: "https://ai-bot.cn/sites/14609.html", category: "search", tags: ["search"] },
  { name: "AMiner", summary: "智谱AI推出的大模型学术平台", href: "https://www.aminer.cn/open/research?f=aibot_search_dr_v1", category: "search", tags: ["search"] },
  { name: "心流", summary: "阿里旗下推出的AI搜索助手", href: "https://iflow.cn/?utm_source=aibot", category: "search", tags: ["search"] },
  { name: "点点", summary: "小红书推出的 AI 搜索应用，主打生活场景", href: "https://ai-bot.cn/diandian", category: "search", tags: ["search"] },
  { name: "Devv", summary: "面向程序员的新一代AI搜索引擎", href: "https://devv.ai/zh?ref=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "知乎直答", summary: "知乎推出的AI搜索引擎，直达问题答案", href: "https://zhida.zhihu.com/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "纳米AI", summary: "360推出的新一代超级AI搜索工具", href: "https://www.n.cn/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "百度AI探索版", summary: "百度推出的深度AI搜索引擎", href: "https://think.baidu.com/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "Felo", summary: "免费AI智能搜索引擎，支持社交联网搜索和多语种问答结果", href: "https://felo.ai/search?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "天工AI搜索", summary: "昆仑万维最新推出的结合大模型的AI搜索引擎", href: "https://tiangong.cn/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "Exa AI", summary: "专门为AI模型设计的搜索引擎平台", href: "https://exa.ai/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "博查AI搜索", summary: "支持多模型的AI搜索引擎", href: "https://bochaai.com", category: "search", tags: ["search"] },
  { name: "WisPaper", summary: "复旦团队推出的 AI 学术搜索工具", href: "https://www.wispaper.ai/?utm_source=aibot", category: "search", tags: ["search"] },
  { name: "CuspAI", summary: "剑桥大学推出的材料学专业AI搜索工具", href: "https://www.cusp.ai/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "博简智慧专利", summary: "AI专利查新检索与撰写平台", href: "https://pagentia.com/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "链企AI", summary: "链企智能推出的AI商业搜索和AI标书写作工具", href: "https://www.lianqiai.cn/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "360AI搜索", summary: "360推出的新一代AI搜索引擎", href: "https://so.360.com/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "问问小宇宙", summary: "小宇宙推出的AI搜索产品", href: "https://ask.xiaoyuzhoufm.com/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "Dexa AI", summary: "AI播客搜索工具", href: "https://dexa.ai/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "XAnswer", summary: "支持生成思维导图的免费AI搜索工具", href: "https://www.xanswer.com/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "Glean", summary: "专为职场人设计的AI搜索引擎", href: "https://www.glean.com/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "AlphaSense", summary: "专为金融专业人士设计的AI搜索工具", href: "https://www.alpha-sense.com/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "Globe Explorer", summary: "结构化AI知识搜索引擎", href: "https://explorer.globe.engineer/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "Reportify", summary: "AI投资研究问答搜索引擎", href: "https://reportify.cc/?ref=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "Phind", summary: "专为开发者设计的AI搜索引擎", href: "https://www.phind.com/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "iAsk AI", summary: "快速准确的AI搜索引擎", href: "https://iask.ai/?utm_source=ai-bot.cn", category: "search", tags: ["search"] },
  { name: "AI大学堂", summary: "科大讯飞推出的在线AI学习平台", href: "https://www.aidaxue.com/?ch=daxue_collection_1", category: "learning", tags: ["learning"] },
  { name: "堆友AI学习", summary: "堆友AI推出的AI设计知识学习网站", href: "https://d.design/study?from=ab13", category: "learning", tags: ["learning"] },
  { name: "AI分享圈", summary: "最好最全的AI免费资源分享网站", href: "https://aisharenet.com", category: "learning", tags: ["learning"] },
  { name: "OpenAI Academy", summary: "OpenAI 推出的免费 AI 学习平台", href: "https://ai-bot.cn/openai-academy", category: "learning", tags: ["learning"] },
  { name: "Day of AI", summary: "麻省理工学院（MIT）推出的免费AI学习平台", href: "https://dayofai.org/?utm_source=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "fast.ai", summary: "免费开源的深度学习和AI学习网站，让每个人都参与到AI！", href: "https://www.fast.ai", category: "learning", tags: ["learning"] },
  { name: "学吧导航", summary: "学习爱好者首选的学霸导航网站", href: "https://www.xue8nav.com/?utm_source=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "Coursera", summary: "知名MOOC平台，提供众多人工智能和机器学习课程", href: "https://www.coursera.org/collections/best-machine-learning-ai?utm_source=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "Elements of AI", summary: "免费在线AI通识学习课程", href: "https://www.elementsofai.com/?utm_source=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "DeepLearning.AI", summary: "深度学习和人工智能学习平台", href: "https://www.deeplearning.ai/?utm_source=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "动手学深度学习", summary: "结合理论与实践的深度学习教材和课程", href: "https://zh.d2l.ai/?utm_source=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "MachineLearningMastery", summary: "免费在线的机器学习平台，提供从基础到高级全面教程", href: "https://machinelearningmastery.com/?utm_source=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "Generative AI for Beginners", summary: "微软推出的面向初学者的免费生成式人工智能课程", href: "https://microsoft.github.io/generative-ai-for-beginners/?utm_source=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "ML for Beginners", summary: "微软推出的免费开源的机器学习课程，GitHub标星7万+", href: "https://microsoft.github.io/ML-For-Beginners/?utm_source=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "Kaggle", summary: "机器学习和数据科学社区", href: "https://www.kaggle.com", category: "learning", tags: ["learning"] },
  { name: "神经网络入门", summary: "Brilliant推出的Introduction to Neural Networks课程", href: "https://brilliant.org/courses/intro-neural-networks/?utm_source=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "Trancy", summary: "AI驱动的语言学习工具", href: "https://trancy.org/zh-cn?referrer=65803e3f65752510b033ade9", category: "learning", tags: ["learning"] },
  { name: "Reading Coach", summary: "微软推出的免费个性化AI阅读学习教练", href: "https://coach.microsoft.com/?ref=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "飞桨AI Studio", summary: "百度推出的AI学习与实训社区", href: "https://aistudio.baidu.com", category: "learning", tags: ["learning"] },
  { name: "腾讯扣叮", summary: "腾讯推出的青少年编程教育平台", href: "https://coding.qq.com/?utm_source=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "阿里云AI学习路线", summary: "阿里云推出的人工智能学习路线（学+测）", href: "https://developer.aliyun.com/learning/roadmap/ai", category: "learning", tags: ["learning"] },
  { name: "Udacity AI学院", summary: "Udacity推出的School of AI，从入门到高级", href: "https://www.udacity.com/school/artificial-intelligence?utm_source=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "Google AI", summary: "Google AI学习平台", href: "https://ai.google", category: "learning", tags: ["learning"] },
  { name: "ShowMeAI知识社区", summary: "人工智能领域的资料库和学习社区", href: "https://www.showmeai.tech/?ref=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "txyz", summary: "AI文献阅读和学术研究辅助平台", href: "https://www.txyz.ai/?utm_source=ai-bot.cn", category: "learning", tags: ["learning"] },
  { name: "Nano Banana", summary: "谷歌推出的图像生成与编辑模型", href: "https://deepmind.google/models/gemini-image/pro", category: "model", tags: ["model"] },
  { name: "Cherry Studio", summary: "开源全能 AI 客户端助手", href: "https://www.cherry-ai.com/?utm_source=ai-bot.cn", category: "model", tags: ["model"] },
  { name: "Ollama", summary: "本地运行Llama和其他大语言模型", href: "https://ollama.ai/?ref=ai-bot.cn", category: "model", tags: ["model"] },
  { name: "AnythingLLM", summary: "开源的全栈 AI 客户端，支持本地部署和API集成", href: "https://ai-bot.cn/anythingllm", category: "model", tags: ["model"] },
  { name: "Chatbox AI", summary: "开源的AI客户端助手，支持多种主流AI模型", href: "https://ai-bot.cn/chatbox-ai", category: "model", tags: ["model"] },
  { name: "讯飞星辰MaaS", summary: "科大讯飞推出的AI模型精调与推理服务平台", href: "https://training.xfyun.cn/modelSquare?utm_source=ai-bot.cn", category: "model", tags: ["model"] },
  { name: "魔搭社区", summary: "阿里达摩院推出的AI模型社区，超过300+开源AI模型", href: "https://www.modelscope.cn/?utm_source=ai-bot.cn", category: "model", tags: ["model"] },
  { name: "豆包大模型", summary: "字节跳动推出的AI大模型家族，包括视频生成、语音视觉、通用语言模型等", href: "https://www.volcengine.com/product/doubao?utm_source=ai-bot.cn", category: "model", tags: ["model"] },
  { name: "无阶未来", summary: "AI应用与弹性算网平台", href: "https://www.aivinla.com/register?code=85307444", category: "model", tags: ["model"] },
  { name: "AutoGPT", summary: "爆火的实现GPT-4完全自主的实验性开源项目，GitHub超10万星", href: "https://agpt.co/?utm_source=ai-bot.cn", category: "model", tags: ["model"] },
  { name: "Jan", summary: "本地运行大模型并进行AI对话的工具，免费开源", href: "https://jan.ai/?ref=ai-bot.cn", category: "model", tags: ["model"] },
  { name: "AgentGPT", summary: "在浏览器中组装、配置和部署自主人工智能的开源项目", href: "https://agentgpt.reworkd.ai/?utm_source=ai-bot.cn", category: "model", tags: ["model"] },
  { name: "OpenBMB", summary: "清华团队支持发起的大规模预训练语言模型库与相关工具", href: "https://www.openbmb.org/home", category: "model", tags: ["model"] },
  { name: "Llama 3", summary: "Meta最新开源推出的新一代大模型", href: "https://llama.meta.com/llama3/?utm_source=ai-bot.cn", category: "model", tags: ["model"] },
  { name: "Gemma", summary: "谷歌推出的新一代轻量级开放模型", href: "https://ai.google.dev/gemma?hl=zh-cn", category: "model", tags: ["model"] },
  { name: "GPT-4o", summary: "OpenAI最新发布的多模态AI大模型，可自然流畅地进行语音对话", href: "https://ai-bot.cn/openai-gpt-4o", category: "model", tags: ["model"] },
  { name: "腾讯混元大模型", summary: "腾讯研发的大语言模型，具备强大的中文创作能力，复杂语境下的逻辑推理能力，以及可靠的任务执行能力", href: "https://hunyuan.tencent.com/?utm_source=ai-bot.cn", category: "model", tags: ["model"] },
  { name: "GPT-4", summary: "OpenAI旗下最新的GPT-4模型", href: "https://ai-bot.cn/sites/49.html", category: "model", tags: ["model"] },
  { name: "DALL·E 3", summary: "OpenAI旗下最新的图像生成模型", href: "https://ai-bot.cn/sites/50.html", category: "model", tags: ["model"] },
  { name: "文心大模型", summary: "百度推出的产业级知识增强大模型", href: "https://wenxin.baidu.com", category: "model", tags: ["model"] },
  { name: "LLaMA", summary: "Meta（Facebook）推出的AI大语言模型", href: "https://github.com/facebookresearch/llama", category: "model", tags: ["model"] },
  { name: "悟道", summary: "智源“悟道”大模型，中国首个+世界最大人工智能大模型", href: "https://www.baai.ac.cn/portal/article/index/cid/49/id/518.html", category: "model", tags: ["model"] },
  { name: "MiracleVision奇想智能", summary: "美图推出的AI视觉大模型，支持AI图像、设计和视频创作", href: "https://www.miraclevision.com/?ref=ai-bot.cn", category: "model", tags: ["model"] },
  { name: "Gradio", summary: "开源的搭建机器学习模型UI界面的Python库", href: "https://gradio.app", category: "model", tags: ["model"] },
  { name: "DeepFloyd IF", summary: "StabilityAI旗下的DeepFloyd团队推出的图片生成模型", href: "https://deepfloyd.ai/deepfloyd-if", category: "model", tags: ["model"] },
  { name: "Cohere", summary: "构建AI产品的大语言模型平台", href: "https://cohere.com", category: "model", tags: ["model"] },
  { name: "序列猴子", summary: "出门问问推出的一款超大规模的语言模型", href: "https://openapi.mobvoi.com/index", category: "model", tags: ["model"] },
  { name: "MagicArena", summary: "字节推出的视觉生成模型对战平台", href: "https://aigcarena.com/?utm_source=ai-bot.cn", category: "eval", tags: ["eval"] },
  { name: "MMLU", summary: "大规模多任务语言理解基准", href: "https://paperswithcode.com/sota/multi-task-language-understanding-on-mmlu", category: "eval", tags: ["eval"] },
  { name: "Open LLM Leaderboard", summary: "Hugging Face推出的开源大模型排行榜单", href: "https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard?utm_source=ai-bot.cn", category: "eval", tags: ["eval"] },
  { name: "C-Eval", summary: "一个全面的中文基础模型评估套件", href: "https://cevalbenchmark.com/index_zh.html#home_zh?utm_source=ai-bot.cn", category: "eval", tags: ["eval"] },
  { name: "FlagEval", summary: "智源研究院推出的FlagEval（天秤）大模型评测平台", href: "https://flageval.baai.ac.cn/#/trending", category: "eval", tags: ["eval"] },
  { name: "SuperCLUE", summary: "中文通用大模型综合性测评基准", href: "https://www.cluebenchmarks.com/static/superclue.html?utm_source=ai-bot.cn", category: "eval", tags: ["eval"] },
  { name: "AGI-Eval", summary: "AI大模型评测社区", href: "https://agi-eval.cn/mvp/home?sourcePage=ai-bot.cn", category: "eval", tags: ["eval"] },
  { name: "OpenCompass", summary: "上海人工智能实验室推出的大模型开放评测体系", href: "https://opencompass.org.cn/leaderboard-llm?utm_source=ai-bot.cn", category: "eval", tags: ["eval"] },
  { name: "CMMLU", summary: "一个综合性的大模型中文评估基准", href: "https://github.com/haonan-li/CMMLU", category: "eval", tags: ["eval"] },
  { name: "MMBench", summary: "全方位的多模态大模型能力评测体系", href: "https://mmbench.opencompass.org.cn/?utm_source=ai-bot.cn", category: "eval", tags: ["eval"] },
  { name: "HELM", summary: "斯坦福大学推出的大模型评测体系", href: "https://crfm.stanford.edu/helm/latest/?utm_source=ai-bot.cn", category: "eval", tags: ["eval"] },
  { name: "LMArena", summary: "AI模型评估平台", href: "https://lmarena.ai/?utm_source=ai-bot.cn", category: "eval", tags: ["eval"] },
  { name: "LLMEval3", summary: "由复旦大学NLP实验室推出的大模型评测基准", href: "http://llmeval.com/index", category: "eval", tags: ["eval"] },
  { name: "H2O EvalGPT", summary: "H2O.ai推出的基于Elo评级方法的大模型评估系统", href: "https://evalgpt.ai", category: "eval", tags: ["eval"] },
  { name: "PubMedQA", summary: "生物医学研究问答数据集和模型得分排行榜", href: "https://pubmedqa.github.io/?utm_source=ai-bot.cn", category: "eval", tags: ["eval"] },
  { name: "PromptPilot", summary: "火山方舟推出的AI提示词解决方案平台", href: "https://promptpilot.volcengine.com/?utm_source=ai-bot.cn", category: "prompt", tags: ["prompt"] },
  { name: "幂简AI提示词商城", summary: "AI提示词交易与管理平台，支持定制", href: "https://prompts.explinks.com/?ref=aibot", category: "prompt", tags: ["prompt"] },
  { name: "提示工程指南", summary: "提示工程指南（Prompt Engine...", href: "https://www.promptingguide.ai/zh", category: "prompt", tags: ["prompt"] },
  { name: "Google AI提示词库", summary: "谷歌推出的AI提示词库", href: "https://cloud.google.com/vertex-ai/generative-ai/docs/prompt-gallery?utm_source=ai-bot.cn", category: "prompt", tags: ["prompt"] },
  { name: "PromptPerfect", summary: "PromptPerfect 是一款专业好...", href: "https://promptperfect.jinaai.cn/?utm_source=ai-bot.cn", category: "prompt", tags: ["prompt"] },
  { name: "Stable Diffusion Prompt Book", summary: "OpenArt平台推出的免费提示词指南手册", href: "https://openart.ai/promptbook", category: "prompt", tags: ["prompt"] },
  { name: "LocalBanana", summary: "专注于AI图像Prompt收集与结构化的平台", href: "https://www.localbanana.io/?utm_source=ai-bot.cn", category: "prompt", tags: ["prompt"] },
  { name: "PromptHero", summary: "AI提示词优化与搜索平台", href: "https://prompthero.com", category: "prompt", tags: ["prompt"] },
  { name: "ClickPrompt", summary: "在线AI提示词设计工具", href: "https://prompt.phodal.com", category: "prompt", tags: ["prompt"] },
  { name: "AI Prompt Generator", summary: "AI Prompt Generator是什么 A...", href: "https://www.aipromptgenerator.net/zh?utm_source=ai-bot.cn", category: "prompt", tags: ["prompt"] },
  { name: "AI Short", summary: "AI提示词管理和共享平台，多种场景的快捷指令", href: "https://www.aishort.top/?utm_source=ai-bot.cn", category: "prompt", tags: ["prompt"] },
  { name: "LangGPT", summary: "LangGPT是什么 LangGPT是一种...", href: "https://github.com/langgptai/LangGPT", category: "prompt", tags: ["prompt"] },
  { name: "Generrated", summary: "AI提示词参考平台", href: "https://generrated.com/?utm_source=ai-bot.cn", category: "prompt", tags: ["prompt"] },
  { name: "PublicPrompts", summary: "PublicPrompts是什么 PublicP...", href: "https://publicprompts.art", category: "prompt", tags: ["prompt"] },
  { name: "Snack Prompt", summary: "输入正确的提示词，可以让Cha...", href: "https://snackprompt.com/?ref=ai-bot.cn", category: "prompt", tags: ["prompt"] },
  { name: "AIPRM", summary: "AI 提示词库和提示词管理工具", href: "https://www.aiprm.com/?utm_source=ai-bot.cn", category: "prompt", tags: ["prompt"] },
  { name: "PromptFolder", summary: "AI提示词生成和管理工具", href: "https://prompt.noonshot.com/?utm_source=ai-bot.cn", category: "prompt", tags: ["prompt"] },
  { name: "AI Prompt Genius", summary: "AI提示词库创建和管理工具", href: "https://www.aipromptgenius.app/?utm_source=ai-bot.cn", category: "prompt", tags: ["prompt"] },
  { name: "PromptBase", summary: "AI Prompt交易平台", href: "https://ai-bot.cn/promptbase", category: "prompt", tags: ["prompt"] },
  { name: "AI Prompt Library", summary: "免费的AI 提示词资源平台", href: "https://moxby.com/ai-prompt-library?utm_source=ai-bot.cn", category: "prompt", tags: ["prompt"] },
  { name: "Awesome ChatGPT Prompts", summary: "AI提示词收集和整理工具", href: "https://prompts.chat/?utm_source=ai-bot.cn", category: "prompt", tags: ["prompt"] },
  { name: "Learning Prompt", summary: "免费的AI提示词学习平台", href: "https://learningprompt.wiki/?utm_source=ai-bot.cn", category: "prompt", tags: ["prompt"] },
];;
